---
# tasks file for guacamole-ansible-role

- name: Check if guacamole client is installed
  stat:
    path: /var/lib/tomcat/webapps/guacamole.war
  register: client_is_installed

- name: Git clone guacamole client
  git:
    repo: https://github.com/apache/incubator-guacamole-client.git
    dest: '{{ guacamole_temp_path }}/client'
    clone: yes
    version: 'tags/{{ guacamole_version }}'
  when: client_is_installed.stat.exists == False

- name: Build from source and install guacamole client
  shell: '{{ item }}'
  args:
    chdir: '{{ guacamole_temp_path }}/client'
    creates: /var/lib/tomcat/webapps/guacamole.war
  register: client_installed
  with_items: ["mvn package", "mkdir -p /usr/share/tomcat/.guacamole/{extensions,lib}", "mkdir -p /etc/guacamole/", "cp guacamole/target/guacamole-{{ guacamole_version }}.war /var/lib/tomcat/webapps/guacamole.war" ]
  when: client_is_installed.stat.exists == False

- name: Check if guacamole-auth-jdbc-mysql is installed
  stat:
    path: /usr/share/tomcat/.guacamole/extensions/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar
  register: auth_jdbc_is_installed

- name: Download guacamole-auth-jdbc-mysql
  get_url:
    url: '{{ guacamole_auth_jdbc_url }}'
    dest: '{{ guacamole_temp_path }}'
    timeout: 120
  when: auth_jdbc_is_installed.stat.exists == False

- name: Unarchive guacamole-auth-jdbc-mysql
  unarchive:
    src: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz'
    remote_src: yes
    dest: '{{ guacamole_temp_path }}'
    creates: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar'
  when: auth_jdbc_is_installed.stat.exists == False

- name: Install guacamole-auth-jdbc-mysql
  copy:
    src: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar'
    dest: /usr/share/tomcat/.guacamole/extensions/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar
    owner: root
    group: tomcat
    mode: 0440
    remote_src: True
  when: auth_jdbc_is_installed.stat.exists == False

- name: Check if mysql-connector-java is installed
  stat:
    path: /usr/share/tomcat/.guacamole/lib/mysql-connector-java-5.1.42-bin.jar
  register: mysql_connector_is_installed

- name: Download mysql-connector-java
  get_url:
    url: '{{ guacamole_mysql_connector_java_url }}'
    dest: '{{ guacamole_temp_path }}'
    timeout: 120
  when: mysql_connector_is_installed.stat.exists == False

- name: Unarchive mysql-connector-java
  unarchive:
    src: '{{ guacamole_temp_path }}/mysql-connector-java-5.1.42.tar.gz'
    remote_src: yes
    dest: '{{ guacamole_temp_path }}'
    creates: '{{ guacamole_temp_path }}/mysql-connector-java-5.1.42/mysql-connector-java-5.1.42-bin.jar'
  when: mysql_connector_is_installed.stat.exists == False

- name: Install mysql-connector-java
  copy:
    src: '{{ guacamole_temp_path }}/mysql-connector-java-5.1.42/mysql-connector-java-5.1.42-bin.jar'
    dest: /usr/share/tomcat/.guacamole/lib/mysql-connector-java-5.1.42-bin.jar
    owner: root
    group: tomcat
    mode: 0440
    remote_src: True
  when: mysql_connector_is_installed.stat.exists == False
